quarkus.http.port=8080
quarkus.management.enabled=true
quarkus.management.port=8090

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./api-shadow;AUTO_SERVER=TRUE
quarkus.hibernate-orm.database.generation=update

mock.optional-field-probability=0.70
mock.max-schema-depth=10
mock.default-array-count=3

mock.faker-suggestions.enabled=true
mock.faker-suggestions.top-k=3
mock.faker-suggestions.model-dir=./models
mock.faker-suggestions.threshold=0.28
mock.faker-suggestions.auto-generate-threshold=0.50
mock.faker-suggestions.model-base-url=https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main
